### ISSUE TITLE
Feature Request: Custom Command Support for Auto-Removal Warnings

### ISSUE THREAD

**Issue by JasonHorkles** [bob7l/Clearlag-Languages#10]
It would be nice to have the ability to use custom commands in the auto-removal stuff, like by adding `- 'time:<time> cmd:<command>'` and it'll execute it.

**Comment by RedstoneFuture** [comment]
Maybe it works with the new `custom-trigger-removal` option at the end of the config:

1. define a new trigger
2. use the `command-executor` part


```
custom-trigger-removal:
  enabled: false
  triggers:
    trigger1:
      trigger-type: tps-trigger
      run-interval: 5
      tps-trigger: 14.0
      tps-recover: 19.0
      jobs:
        command-executor:
          commands:
            - 'lagg killmobs'
            - 'lagg clear'
            - 'lagg halt'
          recover-commands:
            - 'lagg halt'
        entity-clearer:
          execute-job-time: 120
          warnings:
            - 'time:60 msg:&4[ClearLag] &cEntities/drops will be purged in &7+remaining &cseconds!'
            - 'time:100 msg:&4[ClearLag] &cEntities/drops will be purged in &720 &cseconds!'
            - 'time:110 msg:&4[ClearLag] &cEntities/drops will be purged in &710 &cseconds!'
          world-filter:
          # - world <-This world will be ignored during removal
          removeEntities:
            - item
            - zombie !hasName
            - skeleton !hasName
            - pig !hasName
            - cow !hasName
```
